name = "learning-spell"

workers_dev = true
main = "./build/index.js"
compatibility_date = "2024-04-03"
account_id = "ab4ecefcaef1e0ba23455507e91f796b"
node_compat = true

[site]
  bucket = "./public"

[build]
  command = "npm run build"

[[d1_databases]]
  binding = "DB"
  database_name = "learning-spell-db"
  database_id = "d898c14d-4720-4065-9afe-bea63e69ea4f"

[ai]
  binding = "AI"
